CREATE TABLE IF NOT EXISTS users (
  id      BIGSERIAL PRIMARY KEY,
  name    TEXT NOT NULL,
  active  BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS catagories (
  id      BIGSERIAL PRIMARY KEY,
  name    TEXT NOT NULL,
  active  BOOLEAN NOT NULL DEFAULT TRUE
);